{"version":3,"sources":["components/AlertRenderer/ConferenceCallAlert/i18n/ja-JP.ts"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed","callIsRecording"],"mappings":";;;;;;;;;AAAA;;;;;;;;mFAEGA,kCAAqBC,a,EAAgB,6C,0CACrCD,kCAAqBE,oB,EAAuB,6C,0CAC5CF,kCAAqBG,yB,EAA4B,4C,0CACjDH,kCAAqBI,0B,EAA6B,6C,0CAClDJ,kCAAqBK,e,EAAkB,gC,2BAG1C;AACA;AACA;AACA;AACA","sourcesContent":["import conferenceCallErrors from '@ringcentral-integration/commons/modules/ConferenceCall/conferenceCallErrors';\nexport default {\n  [conferenceCallErrors.bringInFailed]: \"予期しないエラーにより、通話をマージできませんでした。後でもう一度やり直してください。\",\n  [conferenceCallErrors.makeConferenceFailed]: \"予期しないエラーにより、通話をマージできませんでした。後でもう一度やり直してください。\",\n  [conferenceCallErrors.terminateConferenceFailed]: \"予期しないエラーにより、会議を終了できませんでした。後でもう一度やり直してください。\",\n  [conferenceCallErrors.removeFromConferenceFailed]: \"予期しないエラーにより、参加者を削除できませんでした。後でもう一度やり直してください。\",\n  [conferenceCallErrors.callIsRecording]: \"通話を録音中です。録音を停止し、もう一度やり直してください。\"\n};\n\n// @key: @#@\"[conferenceCallErrors.bringInFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.makeConferenceFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.terminateConferenceFailed]\"@#@ @source: @#@\"Failed to hangup the conference due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.removeFromConferenceFailed]\"@#@ @source: @#@\"Failed to remove the participant due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.callIsRecording]\"@#@ @source: @#@\"Call recording in progress. Please stop recording and try again.\"@#@\n"],"file":"ja-JP.js"}